name = "VoronoiMeshes"
uuid = "978c199f-fe38-4011-9fe6-317bc1cdd350"
version = "1.0.0-DEV"
authors = ["Felipe A. V. de Bragan√ßa Alves <favbalves@gmail.com> and contributors"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Polyester = "f517fe37-dbe3-4b94-8317-1923a5111588"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
SmallCollections = "2b935e18-93d6-40ac-ae34-fe54c09f00e1"
TensorsLite = "1a1b94bd-d244-45e0-965a-8acfeb92b70f"
TensorsLiteGeometry = "f9cc0174-84f8-4243-a119-6cf6c33db921"
Zeros = "bd1ec220-6eb4-527a-9b49-e79c3db6233b"

[weakdeps]
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
GeometryBasics = "5c1252a2-5f33-56bf-86c9-59e7332b4326"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[sources]
TensorsLite = {rev = "main", url = "https://github.com/favba/TensorsLite.jl"}
TensorsLiteGeometry = {rev = "main", url = "https://github.com/favba/TensorsLiteGeometry.jl"}

[extensions]
DelaunayTriangulationExt = ["DelaunayTriangulation"]
GeometryBasicsExt = ["GeometryBasics"]
MakieExt = "Makie"
NCDatasetsExt = ["NCDatasets"]
ReadVTKExt = ["ReadVTK"]
WriteVTKExt = ["WriteVTK"]

[compat]
DelaunayTriangulation = "1"
GeometryBasics = "0.4, 0.5"
LinearAlgebra = "1"
Makie = "0.23, 0.24"
NCDatasets = "0.14"
Polyester = "0.7"
PrecompileTools = "1"
ReadVTK = "0.2"
SmallCollections = "0.4.1, 0.5"
WriteVTK = "1"
Zeros = "0.4"
julia = "1.10"

[extras]
DelaunayTriangulation = "927a84f5-c5f4-47a5-9785-b46e178433df"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[targets]
test = ["Test", "NCDatasets", "WriteVTK", "ReadVTK", "DelaunayTriangulation"]
